export const ADD_WORDS = 'ADD_WORDS'
export const FETCH_WORDS_REQUEST = 'FETCH_WORDS_REQUEST'
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS'
export const FETCH_WORDS_FAILURE = 'FETCH_WORDS_FAILURE'
